name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - name: Check source code with pre-commit hooks
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uvx pre-commit run --all-files
